version: "3"

services:
  dev:
    container_name: pointcept-dev
    hostname: pointcept-dev
    image: freitas-pointcept:latest
    entrypoint: "./docker-entrypoint.sh"
    command: "bash"
    working_dir: /workspaces/Sculpting
    network_mode: host
    environment: 
      - TERM=xterm-256color
      # - GLOO_SOCKET_IFNAME=enp4s0 
      # - NCCL_SOCKET_IFNAME=enp4s0
      # - SLURM_NODELIST 
      # - SLURM_NODEID  
      # - DIST_URL
      # - WORLD_SIZE  
      # - MASTER_PORT  
      # - MASTER_ADDR
    volumes:
      - .:/workspaces/Sculpting
      - $HOME/.netrc:/root/.netrc
      - $HOME/.bash_history:/root/.bash_history
    shm_size: "32gb"
    privileged: false
    stdin_open: true # docker run -i
    tty: true # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
